# Workspace packages
packages:
  - 'apps/*'
  - 'packages/*'

# Enforce Node and pnpm versions specified in `engines` field of `package.json`
engineStrict: true

# Use whichever pnpm version is available in the environment
pmOnFail: ignore

# Manage peer dependencies explicitly and predictibly
strictPeerDependencies: true
autoInstallPeers: false
resolvePeersFromWorkspaceRoot: false

# Approve specific build scripts
allowBuilds:
  cypress: true
  esbuild: true
  unrs-resolver: true

# Relax minimum release age protection for owned packages
minimumReleaseAgeExclude:
  - '@h5web/*'
  - '@esrf/eslint-config'
  - ndarray@1.1.1
  - '@types/ndarray@1.1.0'

# Save exact dependency versions in `package.json`
savePrefix: ''

# Every project must have these scripts in their `package.json`
requiredScripts:
  - 'lint:eslint'
  - 'lint:tsc'

# Local float16 support, not yet released upstream
overrides:
  '@types/ndarray': '1.1.0'
  h5wasm: 'file:/Users/nathompson7/dev/pkgs/h5wasm-0.10.3-float16.tgz'
